<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
	<div class="form-group">
		<label class="group-name" for="auto_ttl_max_ttl">Max TTL</label>
		<div class="group-controls">
			<select class="w50" name="auto_ttl_max_ttl" id="auto_ttl_max_ttl" required="required">
                <?php
                    $ttlValues = [
                        1200 => '20min',
                        1500 => '25min',
                        1800 => '30min',
                        2700 => '45min',
                        3600 => '1h',
                        5400 => '1.5h',
                        7200 => '2h',
                        10800 => '3h',
                        14400 => '4h',
                        18800 => '5h',
                        21600 => '6h',
                        25200 => '7h',
                        28800 => '8h',
                        36000 => '10h',
                        43200 => '12h',
                        64800 => '18h',
                        86400 => '1d',
                        129600 => '1.5d',
                        172800 => '2d',
                        259200 => '3d',
                        345600 => '4d',
                        432000 => '5d',
                        518400 => '6d',
                        604800 => '1wk',
                        1209600 => '2wk',
                        1814400 => '3wk',
                        2419200 => '4wk',
                        2629744 => '1mo',
                    ];
                ?>
				<?php foreach ($ttlValues as $v => $t) {
				    echo '<option value="'.
				        $v.
				        ($this->maxTTL === $v ? '" selected="selected' : '').
				        '">'.
				        $t.
				        '</option>';
				} ?>
			</select>
		</div>
		<label class="group-name" for="auto_ttl_stats_count">Statistics table rows</label>
		<div class="group-controls">
			<input type="number" min="1" value="<?php echo $this->statsCount; ?>" class="w50" name="auto_ttl_stats_count" id="auto_ttl_stats_count" required="required" />
		</div>
	</div>
	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
			<button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
		</div>
	</div>
</form>

<?php
$now = time();
?>

<div class="table-wrapper">
	<?php $feedsUsingAutoTTL = $this->getStats()->getFeedStats(true); ?>
	<h2>Feeds using AutoTTL (<?php echo count($feedsUsingAutoTTL); ?>)</h2>
	<table>
		<thead>
			<th>Feed</th>
			<th>Average TTL in last 30d</th>
			<th>Status</th>
			<th>Adjusted update TTL</th>
			<th>Last update</th>
			<th>Time until next update</th>
		</thead>
		<tbody>
		<?php foreach ($feedsUsingAutoTTL as $feed) { ?>
		<?php $adjustedTTL = $this->getStats()->calcAdjustedTTL($feed->avgTTL, $feed->dateMax); ?>
		<tr>
			<td>
				<a class="configure" target="_blank" href="<?= _url('subscription', 'feed', 'id', $feed->id) ?>" title="<?= _t('gen.action.manage') ?>"><?= _i('configure') ?></a>
				<?= htmlspecialchars($feed->name, ENT_NOQUOTES, 'UTF-8') ?>
			</td>
			<td>
				<?= ($feed->avgTTL > 0) ? $this->getStats()->humanIntervalFromSeconds($feed->avgTTL) : 'not enough data' ?>
			</td>
			<td>
				<?= $feed->isActive($now) ? 'active' : 'idle' ?>
			</td>
			<td>
				<?= $this->getStats()->humanIntervalFromSeconds($adjustedTTL) ?>
			</td>
			<td>
				<?= ($feed->lastUpdate > 0) ? $this->getStats()->humanIntervalFromSeconds($now - $feed->lastUpdate).' ago' : 'never' ?>
			</td>
			<td>
				<?php
                    if ($feed->lastUpdate > 0) {
                        $timeUntil = $feed->lastUpdate + $adjustedTTL - $now;
                        if ($timeUntil > 0) {
                            $interval = $this->getStats()->humanIntervalFromSeconds($timeUntil);
                            echo $interval;
                        } else {
                            echo 'pending';
                        }
                    } else {
                        echo 'never updated';
                    }
		    ?>
			</td>
		</tr>
		<?php } ?>
		</tbody>
	</table>
</div>

<div class="table-wrapper">
	<?php $feedsNotUsingAutoTTL = $this->getStats()->getFeedStats(false); ?>
	<h2>Feeds not using AutoTTL (<?php echo count($feedsNotUsingAutoTTL); ?>)</h2>
	<p>To enable AutoTTL for a feed, configure the feed's "Do not automatically refresh more often than" option to "By default".</p>
	<table>
		<thead>
			<th>Feed</th>
			<th>Average TTL</th>
			<th>Update TTL</th>
			<th>Last update</th>
			<th>Time until next update</th>
		</thead>
		<tbody>
		<?php foreach ($feedsNotUsingAutoTTL as $feed) { ?>
		<tr>
			<td>
				<a class="configure" target="_blank" href="<?= _url('subscription', 'feed', 'id', $feed->id) ?>" title="<?= _t('gen.action.manage') ?>"><?= _i('configure') ?></a>
				<?= htmlspecialchars($feed->name, ENT_NOQUOTES, 'UTF-8') ?>
			</td>
			<td>
				<?= ($feed->avgTTL > 0) ? $this->getStats()->humanIntervalFromSeconds($feed->avgTTL) : 'not enough data' ?>
			</td>
			<td>
				<?= $this->getStats()->humanIntervalFromSeconds($feed->ttl) ?>
			</td>
			<td>
				<?= ($feed->lastUpdate > 0) ? $this->getStats()->humanIntervalFromSeconds($now - $feed->lastUpdate).' ago' : 'never' ?>
			</td>
			<td>
				<?php
		        if ($feed->lastUpdate > 0) {
		            $timeUntil = $feed->lastUpdate + $feed->ttl - $now;
		            if ($timeUntil > 0) {
		                $interval = $this->getStats()->humanIntervalFromSeconds($timeUntil);
		                echo $interval;
		            } else {
		                echo 'pending';
		            }
		        } else {
		            echo 'never updated';
		        }
		    ?>
			</td>
		</tr>
		<?php } ?>
		</tbody>
	</table>
</div>
