<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
	<div class="form-group">
		<label class="group-name" for="auto_ttl_max_ttl">Max TTL</label>
		<div class="group-controls">
			<select class="w50" name="auto_ttl_max_ttl" id="auto_ttl_max_ttl" required="required">
				<?php foreach (
				    [
				        1200 => '20min',
				        1500 => '25min',
				        1800 => '30min',
				        2700 => '45min',
				        3600 => '1h',
				        5400 => '1.5h',
				        7200 => '2h',
				        10800 => '3h',
				        14400 => '4h',
				        18800 => '5h',
				        21600 => '6h',
				        25200 => '7h',
				        28800 => '8h',
				        36000 => '10h',
				        43200 => '12h',
				        64800 => '18h',
				        86400 => '1d',
				        129600 => '1.5d',
				        172800 => '2d',
				        259200 => '3d',
				        345600 => '4d',
				        432000 => '5d',
				        518400 => '6d',
				        604800 => '1wk',
				        1209600 => '2wk',
				        1814400 => '3wk',
				        2419200 => '4wk',
				        2629744 => '1mo',
				    ]
				    as $v => $t
				) {
				    echo '<option value="' .
				        $v .
				        ((int)FreshRSS_Context::$user_conf->auto_ttl_max_ttl === $v ? '" selected="selected' : '') .
				        '">' .
				        $t .
				        '</option>';
				} ?>
			</select>
		</div>
	</div>
	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
			<button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
		</div>
	</div>
</form>

<div class="table-wrapper">
	<h2>Feed frequency statistics</h2>
	<table>
		<thead>
			<th>Feed</th>
			<th>Average TTL</th>
			<th>Adjusted TTL</th>
		</thead>
		<tbody>
		<?php foreach ($this->getStats()->fetchAllStats() as $feed) { ?>
		<tr>
			<td>
				<?= htmlspecialchars($feed['name'], ENT_NOQUOTES, 'UTF-8') ?>
			</td>
			<td>
				<?= $feed['avg_ttl'] ?>s
			</td>
			<td>
				<?= $feed['adjusted_ttl'] ?>s
			</td>
		</tr>
		<?php } ?>
		</tbody>
	</table>
</div>
