---
services:
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: freshrss
      MYSQL_PASSWORD: freshrss
      MYSQL_DATABASE: freshrss
    tmpfs:
      - /var/lib/mysql:uid=999,gid=999
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 1s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: freshrss
      POSTGRES_USER: freshrss
      POSTGRES_DB: freshrss
    tmpfs:
      - /var/lib/postgresql:uid=999,gid=999
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U freshrss"]
      interval: 1s
      timeout: 5s
      retries: 10

  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - .:/var/www/FreshRSS/extensions/FreshRSS-AutoTTL
    environment:
      CRON_MIN: '*'
      TRUSTED_PROXY: 172.16.0.1/12 192.168.0.1/16
      FRESHRSS_ENV: development
    ports:
      - "8080:80"
    healthcheck:
      test: cli/health.php
      interval: 1s
      timeout: 5s
      retries: 10

  composer:
    image: composer
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - .:/app

  wiremock:
    image: wiremock/wiremock:latest-alpine
    volumes:
      - ./wiremock:/home/wiremock
    command: --local-response-templating
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:8080/__admin/"]
      interval: 10s
      timeout: 5s
      retries: 5
